CREATE TABLE IF NOT EXISTS  ODONTOLOGOS (
ID INT AUTO_INCREMENT PRIMARY KEY,
MATRICULA INT,
NOMBRE VARCHAR(100),
APELLIDO VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS  PACIENTES (
ID INT AUTO_INCREMENT PRIMARY KEY,
NOMBRE VARCHAR(100),
APELLIDO VARCHAR(100),
DOMICILIO VARCHAR(100),
DNI INT,
FECHAALTA DATE
);
